### ISSUE TITLE
[Bug]: 求助同步功能无法连接服务器

### ISSUE THREAD

**Issue by disburden** [lyswhut/lx-music-desktop#2124]
### 解决方案检查

- [X] 我已阅读常见问题(<https://lyswhut.github.io/lx-music-doc/desktop/faq>)，并没有找到解决方案
- [X] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)，并没有发现类似的问题

### 预期行为

这是我的docker-compose配置文件内容
```yaml
version: '3'
services:
  lx-music:
    container_name: lx-music
    image: lyswhut/lx-music-sync-server
    ports:
      - "18889:9527"
    environment:
      - BIND_IP=0.0.0.0
      - LX_USER_user1=xxxx
    restart: always
    volumes:
      - $PWD/data:/server/data
```
docker运行正常
![截图_选择区域_20241121141253](https://github.com/user-attachments/assets/39acf652-48ea-456b-a7fe-eccc234c4903)
但是客户端就是死活提示连不上服务器
![截图_选择区域_20241121141514](https://github.com/user-attachments/assets/63775e2b-220b-4f0d-8852-60f685bb376d)
用的cloudflare解析域名,在浏览器中直接输入同步服务器地址会返回字符串"Forbidden"
求助如何正确配置同步服务器...

### 实际行为

原本希望能正常连接同步服务器,但一直提示连接失败

### Lx Music 版本

2.9.0

### 操作系统版本

Linux dao 6.9.6-amd64-desktop-rolling #23.01.01.02 SMP PREEMPT_DYNAMIC Tue Jul 23 12:20:02 CST 2024 x86_64 GNU/Linux
