### ISSUE TITLE
添加winget安装脚本

### ISSUE THREAD

**Issue by songtao1873** [lyswhut/lx-music-desktop#524]
**解决方案检查**

- [x] 我已阅读常见问题(<https://github.com/lyswhut/lx-music-desktop/blob/master/FAQ.md>)
- [x] 我已搜索issue列表(<https://github.com/lyswhut/lx-music-desktop/issues?utf8=✓&q=>)

**描述您想要的解决方案**

请求添加winget-pkg安装脚本以此可以命令一键安装

**描述您考虑过的替代方案**

**其他内容**

**Comment by lyswhut** [comment]
我对winget-pkg并不了解，你可以说下怎么弄这个东西吗😂

**Comment by songtao1873** [comment]
1. fork [winget-pkgs存储库](https://github.com/microsoft/winget-pkgs)
2. 新建[manifests](https://github.com/microsoft/winget-pkgs/blob/master/manifests)对应的文件
   - 按照规范,应该新建 `winget-pkgs/manifests/l/lyswhut/LX-Music/1.10.2/lyswhut.LXMusic.installer.yaml`内容对应如下

      ```yaml
      Id: lyswhut.lx-music # Publisher.package format.
      Publisher: lyswhut # The name of the publisher.
      Name: LX-Music # The name of the application.
      AppMoniker: lx-music # The common name someone may use to search for the package.
      Version: 1.10.2 # Version numbering format for package version.
      License: Apache-2.0 License # The open source license or copyright.
      LicenseUrl: https://github.com/lyswhut/lx-music-desktop/LICENSE # Valid secure URL to license.
      Description: A music software developed based on Electron + Vue # Description of the package.
      Homepage: https://github.com/lyswhut/lx-music-desktop # Valid secure URL for the package.
      Tags: 
      - music
      InstallerType: inno # Enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx).
      Installers: # Nested map of keys for specific installer.
      - Arch: x64 # Enumeration of supported architectures.
        Url: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.10.2/lx-music-desktop-v1.10.2-x64-Setup.exe # Path to download installation file.
        Sha256: 9FB6B1335AB717111E1F42A6F64DD26A5BF554780BF97C3475B6C3CD52D1657D # SHA256 calculated from installer.
        Scope: user # Experimental.
      - Arch: x64 # Enumeration of supported architectures.
        Url: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.10.2/lx-music-desktop-v1.10.2-x64-Setup.exe # Path to download installation file.
        Sha256: 9FB6B1335AB717111E1F42A6F64DD26A5BF554780BF97C3475B6C3CD52D1657D # SHA256 calculated from installer.
        Scope: machine # Experimental.
      - Arch: x86 # Enumeration of supported architectures.
        Url: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.10.2/lx-music-desktop-v1.10.2-x86-Setup.exe # Path to download installation file.
        Sha256: 0F6992186D96F6C361613C502D902EC55F95642E88F7DBE60336AB02BA705AA5 # SHA256 calculated from installer.
        Scope: user # Experimental.
      - Arch: x86 # Enumeration of supported architectures.
        Url: https://github.com/lyswhut/lx-music-desktop/releases/download/v1.10.2/lx-music-desktop-v1.10.2-x86-Setup.exe # Path to download installation file.
        Sha256: 0F6992186D96F6C361613C502D902EC55F95642E88F7DBE60336AB02BA705AA5 # SHA256 calculated from installer.
        Scope: machine # Experimental.
      ManifestVersion: 1.0.0 # Version number format for manifest version.
      ```
3. 此后按照微软官方[Wiki](https://docs.microsoft.com/zh-cn/windows/package-manager/package/repository)提交,并且拉取到到主分支
